# Generated by Django 5.2.1 on 2025-05-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="menu",
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="named_url",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
