# Generated by Django 5.2.1 on 2025-05-14 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0002_remove_menuitem_menu_alter_menuitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ("title",),
                "verbose_name": "Меню",
                "verbose_name_plural": "Список меню",
            },
        ),
        migrations.AddField(
            model_name="menuitem",
            name="menu_name",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Меню для группировки"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="menu_app.menuitem",
                verbose_name="Название меню",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название меню"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(
                max_length=255, verbose_name="Ссылка перехода по меню"
            ),
        ),
    ]
