# Generated by Django 5.2.1 on 2025-05-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0004_menu_item_delete_menuitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={},
        ),
        migrations.RemoveField(
            model_name="menu",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="title",
        ),
        migrations.AddField(
            model_name="menu",
            name="name",
            field=models.CharField(
                default=1, max_length=100, unique=True, verbose_name="Название меню"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название пункта"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="URL (явный)"
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Named URL (name из urls.py)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu_app.menu",
                        verbose_name="Меню",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menu_app.menuitem",
                        verbose_name="Родительский пункт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ["order", "id"],
            },
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
