# Generated by Django 5.2.1 on 2025-05-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0005_alter_menu_options_remove_menu_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={
                "ordering": ["id"],
                "verbose_name": "Mеню",
                "verbose_name_plural": "Список меню",
            },
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="order",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="named_url",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="Named URL (name из urls.py)"
            ),
        ),
    ]
