# Generated by Django 5.2.1 on 2025-05-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0006_alter_menu_options_alter_menuitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="named_url",
            field=models.SlugField(
                blank=True,
                max_length=200,
                unique=True,
                verbose_name="Named URL (name из urls.py)",
            ),
        ),
    ]
